#!/usr/bin/env python3
"""Generate Tests/protected/step5_<name>.yaml from step5_cases.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import step5_cases as C  # noqa: E402


def gen(name, ids):
    L = ["# GENERATED by Tests/tools/gen_step5_scenarios.py - do not edit.",
         f"name: 'Step 5 - {name}'", "version: 1", "author: 'STM32 fault-injection study'", "steps:",
         "  - wait-serial: 'system_ready'"]
    if not ids:
        L.append(f"  - delay: {C.FP_MS}ms")
    else:
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        for i, fid in enumerate(ids):
            L.append(f'  - write-serial: "FAULT {fid}\\n"')
            L.append(f"  - wait-serial: 'EXP={fid}_001 state={C.FINAL_STATE[fid]}'")
            L.append(f"  - delay: {C.GAP_MS if i < len(ids) - 1 else C.TAIL_MS}ms")
    os.makedirs("Tests/protected", exist_ok=True)
    path = f"Tests/protected/step5_{name}.yaml"
    open(path, "w").write("\n".join(L) + "\n")
    return path


if __name__ == "__main__":
    for n, ids in C.SCENARIOS.items():
        print("wrote", gen(n, ids))
