#!/usr/bin/env python3
"""Generate Tests/baseline/step4_<name>.yaml from step4_cases.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import step4_cases as C  # noqa: E402


def gen(name, ids):
    L = [f"# GENERATED by Tests/tools/gen_step4_scenarios.py - do not edit.",
         f"name: 'Step 4 - {name}'", "version: 1", "author: 'STM32 fault-injection study'", "steps:",
         "  - wait-serial: 'system_ready'", f"  - delay: {C.START_DELAY_MS}ms"]
    for i, fid in enumerate(ids):
        L.append(f'  - write-serial: "FAULT {fid}\\n"')
        L.append(f"  - wait-serial: 'EXP={fid}_001 state={C.FINAL_STATE[fid]}'")
        L.append(f"  - delay: {C.GAP_MS if i < len(ids) - 1 else C.TAIL_MS}ms")
    path = f"Tests/baseline/step4_{name}.yaml"
    open(path, "w").write("\n".join(L) + "\n")
    return path


if __name__ == "__main__":
    for n, ids in C.SCENARIOS.items():
        print("wrote", gen(n, ids))
