#!/usr/bin/env python3
"""Scenario files for the follow-up campaigns:
  Tests/equiv/e_<fault>.yaml     one fault per simulation, commanded 2.5 s after system_ready, for BOTH builds, so that the baseline and the
                                 protected campaign inject at the same time of the run (Step 7 condition equivalence); two variants:
                                 *_base.yaml waits for the framework state, *_rec.yaml also waits for the recovery to finish.
  Tests/timer/t_<name>.yaml      timer-triggered injection (`FAULT_AT <ID> <ms>`, injected in the TIM4 interrupt) of study faults on the baseline build."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import step4_cases as S4  # noqa: E402
import step6_cases as S6  # noqa: E402

EQUIV_FAULTS = {"mem01": "MEM-01", "mem02": "MEM-02", "cpu01": "CPU-01", "cpu02": "CPU-02", "tim01": "TIM-01", "tim02": "TIM-02",
                "data01": "DATA-01", "data02": "DATA-02", "periph": "PERIPH-01"}
# runs that already exist with the 2.5 s timing in the Step 4 / Step 6 campaigns (scenario name there): reused, not repeated
REUSE_BASE = {"mem02": "mem02", "cpu01": "cpu01", "cpu02": "cpu02", "tim01": "tim01", "tim02": "tim02"}
REUSE_REC = {"cpu01": "cpu01", "cpu02": "cpu02", "tim01": "tim01", "periph": "periph"}

TIMER = {
    "a": [("MEM-01", 800), ("DATA-01", 800), ("DATA-02", 800), ("PERIPH-01", 800)],
    "b": [("TIM-02", 800)],
    "c": [("TIM-01", 800)],
}
TIMER_FINAL = {"MEM-01": "COMPLETED", "DATA-01": "COMPLETED", "DATA-02": "COMPLETED", "PERIPH-01": "COMPLETED", "TIM-02": "COMPLETED", "TIM-01": "INJECTED"}


def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write("\n".join(lines) + "\n")


def equiv(name, fid, variant):
    L = [f"# GENERATED by Tests/tools/gen_followup_scenarios.py - do not edit.", f"name: 'Equivalent-timing {fid} ({variant})'", "version: 1",
         "author: 'STM32 fault-injection study'", "steps:", "  - wait-serial: 'system_ready'", f"  - delay: {S4.START_DELAY_MS}ms", f'  - write-serial: "FAULT {fid}\\n"']
    if variant == "base":
        L.append(f"  - wait-serial: 'EXP={fid}_001 state={S4.FINAL_STATE[fid]}'")
    else:
        L.append(f"  - wait-serial: 'EXP={fid}_001 attempt'")
        L.append(f"  - wait-serial: '{S6.RECOVERY_WAIT.get(fid, 'state=COMPLETE success=1') if fid != 'PERIPH-01' else 'action=i2c_bus_recovery state=COMPLETE success=1'}'")
    L.append(f"  - delay: {S4.TAIL_MS}ms")
    write(f"Tests/equiv/e_{name}_{variant}.yaml", L)


def timer(name, items):
    L = ["# GENERATED by Tests/tools/gen_followup_scenarios.py - do not edit.", f"name: 'Timer-triggered study faults ({name})'", "version: 1",
         "author: 'STM32 fault-injection study'", "steps:", "  - wait-serial: 'system_ready'", f"  - delay: {S4.START_DELAY_MS}ms"]
    for i, (fid, ms) in enumerate(items):
        L.append(f'  - write-serial: "FAULT_AT {fid} {ms}\\n"')
        L.append(f"  - wait-serial: 'EXP={fid}_001 state={TIMER_FINAL[fid]}'")
        L.append(f"  - delay: {S4.GAP_MS if i < len(items) - 1 else S4.TAIL_MS}ms")
    write(f"Tests/timer/t_{name}.yaml", L)


if __name__ == "__main__":
    for n, f in EQUIV_FAULTS.items():
        for v in ("base", "rec"):
            equiv(n, f, v)
    for n, items in TIMER.items():
        timer(n, items)
    print("wrote", len(EQUIV_FAULTS) * 2, "equiv and", len(TIMER), "timer scenarios")
