#!/usr/bin/env python3
"""Generate Tests/recovery/step6_<name>.yaml from step6_cases.py."""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import step6_cases as C  # noqa: E402


def cmd(L, fid):
    L.append(f'  - write-serial: "FAULT {fid}\\n"')


def gen(name, ids):
    L = ["# GENERATED by Tests/tools/gen_step6_scenarios.py - do not edit.",
         f"name: 'Step 6 - {name}'", "version: 1", "author: 'STM32 fault-injection study'", "steps:",
         "  - wait-serial: 'system_ready'"]
    if name == "fp":
        L.append(f"  - delay: {C.FP_MS}ms")
    elif name == "g1":
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        for i, fid in enumerate(ids):
            cmd(L, fid)
            L.append(f"  - wait-serial: 'EXP={fid}_001 attempt'")
            L.append(f"  - wait-serial: '{C.RECOVERY_WAIT[fid]}'")
            L.append(f"  - delay: {C.GAP_MS if i < len(ids) - 1 else C.TAIL_MS}ms")
    elif name in ("tim01", "cpu01", "cpu02", "cpu03"):
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        cmd(L, ids[0])
        L.append("  - wait-serial: 'state=COMPLETE success=1'")
        L.append(f"  - delay: {C.TAIL_MS}ms")
    elif name == "periph":
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        cmd(L, "PERIPH-01")
        L.append("  - wait-serial: 'action=i2c_bus_recovery state=COMPLETE success=1'")
        L.append(f"  - delay: {C.TAIL_MS}ms")
    elif name == "safe_rep":
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        for i in range(3):
            cmd(L, "TIM-01")
            L.append("  - wait-serial: 'state=COMPLETE success=1'")
            L.append("  - delay: 1000ms")
        cmd(L, "TIM-01")
        L.append("  - wait-serial: 'state=ENTERED'")
        L.append("  - delay: 4500ms")
    elif name == "safe_fail":
        L.append(f"  - delay: {C.START_DELAY_MS}ms")
        cmd(L, "TIM-03")
        L.append("  - wait-serial: 'state=ENTERED'")
        L.append("  - delay: 4500ms")
    os.makedirs(C.SCEN_DIR, exist_ok=True)
    path = f"{C.SCEN_DIR}/step6_{name}.yaml"
    open(path, "w").write("\n".join(L) + "\n")
    return path


if __name__ == "__main__":
    for n, ids in C.SCENARIOS.items():
        print("wrote", gen(n, ids))
