#!/usr/bin/env python3
"""Generate Tests/baseline/step3_framework.yaml from step3_cases.py.

Order (all timing in simulated time, so every run is identical):
  1. rejected commands (invalid / missing / malformed / line-level)
  2. every registered study fault ID via UART (accepted; ends not_implemented)
  3. UART-triggered FI-TEST x3, then a quiet polling window
  4. timer-triggered FI-TEST with a busy rejection while it is armed,
     then a second timer delay
  5. STATUS on demand and one periodic STATUS"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import step3_cases as C  # noqa: E402

OUT = "Tests/baseline/step3_framework.yaml"


def send(lines, data):
    if isinstance(data, bytes):
        lines.append(f"  - write-serial: [{', '.join(str(b) for b in data + b'\n')}]")
    else:
        assert '"' not in data and "\\" not in data
        lines.append(f'  - write-serial: "{data}\\n"')


def wait(lines, text):
    assert "[" not in text and "]" not in text, text
    lines.append(f"  - wait-serial: '{text}'")


def main():
    L = ["# GENERATED by Tests/tools/gen_step3_scenario.py from step3_cases.py - do not edit.",
         "# Step 3 acceptance scenario (fault-injection framework, FI-TEST + registered IDs).",
         "name: 'Step 3 - fault-injection framework'", "version: 1",
         "author: 'STM32 fault-injection study'", "steps:"]
    wait(L, "system_ready")
    L.append("  - delay: 1000ms")

    for line, _grp, cmd, reason, arg in C.REJECT_CASES:
        send(L, line)
        wait(L, f"result=rejected cmd={cmd} reason={reason}" + (f" arg={arg}" if arg else ""))
        L.append("  - delay: 50ms")
    for data, _grp, reason in C.LINE_REJECT_CASES:
        send(L, data)
        wait(L, f"reason={reason}")
        L.append("  - delay: 50ms")

    for fid in C.STUDY_IDS:
        send(L, f"FAULT {fid}")
        wait(L, f"EXP={fid}_001 state=ERROR reason=not_implemented")
        L.append("  - delay: 50ms")

    for i in range(1, C.UART_INJECTIONS + 1):
        send(L, "FAULT FI-TEST")
        wait(L, f"EXP=FI-TEST_{i:03d} state=COMPLETED")
        L.append("  - delay: 100ms")
    L.append(f"  - delay: {C.POLL_WINDOW_MS}ms")

    n = C.UART_INJECTIONS
    for k, d in enumerate(C.TIMER_DELAYS_MS):
        n += 1
        send(L, f"FAULT_AT FI-TEST {d}")
        wait(L, f"EXP=FI-TEST_{n:03d} state=ARMED")
        if k == 0:
            send(L, "FAULT FI-TEST")
            wait(L, "reason=busy")
        wait(L, f"EXP=FI-TEST_{n:03d} state=COMPLETED")
        L.append("  - delay: 100ms")

    send(L, "STATUS")
    wait(L, "src=cmd")
    L.append("  - delay: 1500ms")
    wait(L, "src=periodic")
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
