#!/usr/bin/env python3
"""Write results/raw/README.md: every raw result directory, whether it is complete, and which one the reports use.

A directory is complete when every scenario log of its campaign exists, is non-empty and the run ended normally
(wokwi-cli exit line present). Incomplete ones are kept as evidence of what went wrong (quota, HTTP 503, DNS) but are
never used by the checkers or by make_report.py (they pick the newest complete directory)."""
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import eval_step7 as E  # noqa: E402
import step5_cases as C5  # noqa: E402

CAMPAIGNS = [
    ("step2", "Step 2 suite (smoke, i2ctest, uartrx, 3 baseline runs)", ["baseline_run1", "baseline_run2", "baseline_run3", "i2ctest", "smoke", "uartrx"]),
    ("step3", "Step 3 suite (3 framework runs + 3 GDB runs)", [f"scenario_run{i}" for i in (1, 2, 3)] + [f"gdb_run{i}" for i in (1, 2, 3)]),
    ("step4", "Step 4 baseline campaign (6 scenarios x 3)", [f"{s}_run{i}" for s in ("group", "tim01", "tim02", "mem02", "cpu01", "cpu02") for i in (1, 2, 3)]),
    ("step5", "Step 5 detection campaign (7 scenarios x 3)", [f"{s}_run{i}" for s in C5.SCENARIOS for i in (1, 2, 3)]),
    ("step6", "Step 6/7 recovery campaign (9 scenarios x 3)", [f"{s}_run{i}" for s in E.C6.SCENARIOS for i in (1, 2, 3)]),
]


def status(d, logs):
    missing, empty, quota = [], [], 0
    for n in logs:
        f = f"{d}/{n}.log"
        if not os.path.exists(f):
            missing.append(n)
        elif os.path.getsize(f) == 0:
            empty.append(n)
    quota = len(glob.glob(f"{d}/*.quota.txt")) + sum(1 for f in glob.glob(f"{d}/*.attempt*.txt") if "used up your Free plan" in open(f, errors="replace").read())
    retries = len(glob.glob(f"{d}/*.attempt*.txt"))
    return missing, empty, retries, quota


def main():
    out = ["# Raw results index", "", "Generated by `Tests/tools/make_index.py` (run by `make report`). One directory per run of a suite; the reports and checkers use the",
           "**newest complete** directory of each campaign (marked `canonical`). Incomplete directories stay as evidence of infrastructure failures",
           "(Wokwi CI quota, HTTP 503, DNS errors) and are not used.", ""]
    for key, title, logs in CAMPAIGNS:
        out += [f"## {key}: {title}", "", "| Directory | Logs present | Missing/empty | Retries (attempt files) | Status |", "|---|---:|---|---:|---|"]
        dirs = sorted(d for d in glob.glob(f"results/raw/{key}/*") if os.path.isdir(d) and not os.path.basename(d) in ("probes",))
        stats = []
        for d in dirs:
            missing, empty, retries, quota = status(d, logs)
            complete = not missing and not empty
            stats.append((d, complete, missing, empty, retries, quota))
        canon = next((d for d, ok, *_ in reversed(stats) if ok and not os.path.basename(d).startswith("partial")), None)
        for d, ok, missing, empty, retries, quota in stats:
            st = "canonical (used by the reports)" if d == canon else ("complete, superseded by a newer run" if ok else "INCOMPLETE" + (" (quota exhausted)" if quota else ""))
            bad = ", ".join(missing + [e + " (empty)" for e in empty]) or "-"
            out.append(f"| `{os.path.basename(d)}` | {len(logs) - len(missing) - len(empty)}/{len(logs)} | {bad[:90]} | {retries} | {st} |")
        out.append("")
    out += ["Other directories: `results/raw/*/probes` = one-off simulator probes (see the README inside), `results/raw/smoke`, `results/raw/i2ctest` = Step 0/1 logs.", ""]
    open("results/raw/README.md", "w").write("\n".join(out))
    print("wrote results/raw/README.md")


if __name__ == "__main__":
    main()
